apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: {{ .Values.image.tag }}
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
        tag: {{ .Values.image.tag }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: {{ .Values.service.protocol }}
        livenessProbe:
           httpGet:
             path: {{ .Values.livenessProbe }}
             port: {{ .Values.containerPort }}
        readinessProbe:
           httpGet:
             path: {{ .Values.readinessProbe }}
             port: {{ .Values.containerPort }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.cpu }}
            cpu: {{ .Values.resources.requests.memory }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}

